name: "Load Environment Variables"
description: "Loads the .env file"
inputs:
  azureDeployRepoToken:
    description: "The token of the azure-deploy repository"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout common-deploy
      uses: actions/checkout@v4
      with:
        repository: Redpill-Linpro-DK/marw-test-azure-deploy@main
        token: ${{ inputs.azureDeployRepoToken }}
        path: common-repo

    - name: Load environment variables
      uses: ./common-repo/.github/actions/loadEnvVariables
      with:
        rootDir: common-repo
