name: "Load Environment Variables"
description: "Loads the .env file"
runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: |
        n=${{ inputs.azureDeployRepoToken }}
        echo size of input is: ${#n}
    - name: Checkout common-deploy
      uses: actions/checkout@v4
      with:
        repository: Redpill-Linpro-DK/marw-test-azure-deploy@test_common_var
        path: tmp-repo

    - name: Load environment variables
      uses: ./tmp-repo/.github/actions/loadEnvVariables
      with:
        rootDir: tmp-repo
