name: Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  load-variables:
    name: Load Variables
    uses: Redpill-Linpro-DK/marw-test-azure-deploy/.github/workflows/load-variables.yml@main
    with:
      variables_dir: "../variables"
      branch: ${{ github.ref_name }}

  deploy:
    name: Deploy to Azure
    needs: load-variables  # Waits for the load-variables job to complete
    runs-on: ubuntu-latest  # Specify the OS for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Check out the code in the repository

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.DIH_FAIR_AZURE_CREDENTIALS_DEV }}

    - name: Ensure resource group exists and deploy resources
      run: |
        # Ensure the resource group exists
        az group create --name MARWTESTFROMGITHUB --location $VAR_LOCATION

        # Deploy the resources using the Bicep file
        az deployment group create \
          --resource-group MARWTESTFROMGITHUB \
          --template-file main.bicep
